const STARS_NUM = 30;

const MIN_RADIUS = 2;
const MAX_RADIUS = 3;

const MIN_SPEED = 0.8;
const MAX_SPEED = 1.2;

const MIN_ROTATION_RADIUS = 5;
const MAX_ROTATION_RADIUS = 900;

const MIN_DISTANCE = MAX_RADIUS * 100;

const ROTATION_VELOCITY = 0.002;
